#!/bin/bash

#function: test_image
test_image () {
    case $1 in
     1|01)
       echo a
     ;;
     2|02)
       echo b
     ;;
     3|03)
       echo c
     ;;
     4|04)
       echo c
     ;;
     5|05)
       echo c
     ;;
     6|06)
       echo d
     ;;
     7|07)
       echo e
     ;;
     8|08)
       echo e
     ;;
     11)
       echo 0
     ;;
     12)
       echo h
     ;;
     13|14)
       echo g
     ;;
     15)
       echo l
     ;;
     16|17)
       echo k
     ;;
     18|26)
       echo i
     ;;
     19)
       echo p
     ;;
     20|21|23)
       echo o
     ;;
     22)
       echo r
     ;;
     24|31)
       echo E
     ;;
     25)
       echo u
     ;;
     29)
       echo v
     ;;
     30)
       echo 5
     ;;
     32)
       echo 6
     ;;
     33)
       echo A
     ;;
     34|36|37)
       echo B
     ;;
     35|38)
       echo C
     ;;
     39|40)
       echo G
     ;;
     41|42)
       echo K
     ;;
     43|44)
       echo O
     ;;
    esac
} 

#put your accuweather rss address here
address="http://rss.accuweather.com/rss/liveweather_rss.asp?metric=1&locCode=cordoba"

WEATHER_FILE_LOCATION=$HOME/.conky/scripts/accu_weather/rss/weather_raw
WEATHER_DATE_LOCATION=$HOME/.conky/scripts/accu_weather/rss/weather
wget -q -O $WEATHER_FILE_LOCATION $address


if [[ -s $WEATHER_FILE_LOCATION ]]; then

    egrep 'Currently|Forecast<\/title>|_31x31.gif' $WEATHER_FILE_LOCATION > $WEATHER_DATE_LOCATION
    sed -i '/AccuWeather\|Currently in/d' $WEATHER_DATE_LOCATION
    sed -i -e 's/^[ \t]*//g' -e 's/<title>\|<\/title>\|<description>\|<\/description>//g' $WEATHER_DATE_LOCATION
    sed -i -e 's/&lt;img src="/\n/g' $WEATHER_DATE_LOCATION
    sed -i '/^$/d' $WEATHER_DATE_LOCATION
    sed -i -e 's/_31x31.*$//g' -e 's/^.*\/icons\///g' $WEATHER_DATE_LOCATION
    sed -i -e '1s/.$//' -e '3s/.$//' -e '6s/.$//' $WEATHER_DATE_LOCATION
    for (( i=2; i<=8; i+=3 )); do
        im=$(sed -n ${i}p $WEATHER_DATE_LOCATION)
        sed -i $i"s/^.*$/$(test_image $im)/" $WEATHER_DATE_LOCATION
    done

fi
